//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.13 at 04:45:07 PM MESZ 
//


package org.comtel.fritz.connect.devicelist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.comtel.fritz.connect.devicelist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.comtel.fritz.connect.devicelist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Devicelist.Group.Groupinfo }
     * 
     */
    public Devicelist.Group.Groupinfo createDevicelistGroupGroupinfo() {
        return new Devicelist.Group.Groupinfo();
    }

    /**
     * Create an instance of {@link Devicelist }
     * 
     */
    public Devicelist createDevicelist() {
        return new Devicelist();
    }

    /**
     * Create an instance of {@link Devicelist.Device }
     * 
     */
    public Devicelist.Device createDevicelistDevice() {
        return new Devicelist.Device();
    }

    /**
     * Create an instance of {@link Devicelist.Device.Powermeter }
     * 
     */
    public Devicelist.Device.Powermeter createDevicelistDevicePowermeter() {
        return new Devicelist.Device.Powermeter();
    }

    /**
     * Create an instance of {@link Devicelist.Device.Temperature }
     * 
     */
    public Devicelist.Device.Temperature createDevicelistDeviceTemperature() {
        return new Devicelist.Device.Temperature();
    }

    /**
     * Create an instance of {@link Switch }
     * 
     */
    public Switch createSwitch() {
        return new Switch();
    }

    /**
     * Create an instance of {@link Devicelist.Group }
     * 
     */
    public Devicelist.Group createDevicelistGroup() {
        return new Devicelist.Group();
    }

}
